# Generated by Django 4.1.7 on 2023-04-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stech', '0003_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
